
import { Language, LetterData, UIContent, LevelConfig } from './types';

export const PERSIA_ALPHABET: LetterData[] = [
  { char: 'ا', name: 'Alef', transliteration: 'ā / a', isolated: 'ا', initial: 'آ', medial: 'ـا', final: 'ـا', exampleWord: 'آب', exampleTransliteration: 'āb', exampleMeaningEn: 'Water', exampleMeaningZh: '水' },
  { char: 'ب', name: 'Be', transliteration: 'b', isolated: 'ب', initial: 'بـ', medial: 'ـبـ', final: 'ـب', exampleWord: 'باران', exampleTransliteration: 'bārān', exampleMeaningEn: 'Rain', exampleMeaningZh: '雨' },
  { char: 'پ', name: 'Pe', transliteration: 'p', isolated: 'پ', initial: 'پـ', medial: 'ـپـ', final: 'ـپ', exampleWord: 'پدر', exampleTransliteration: 'pedar', exampleMeaningEn: 'Father', exampleMeaningZh: '父親' },
  { char: 'ت', name: 'Te', transliteration: 't', isolated: 'ت', initial: 'تـ', medial: 'ـتـ', final: 'ـت', exampleWord: 'توت', exampleTransliteration: 'tut', exampleMeaningEn: 'Berry', exampleMeaningZh: '漿果' },
  { char: 'ث', name: 'Se', transliteration: 's', isolated: 'ث', initial: 'ثـ', medial: 'ـثـ', final: 'ـث', exampleWord: 'ثروت', exampleTransliteration: 'servat', exampleMeaningEn: 'Wealth', exampleMeaningZh: '財富' },
  { char: 'ج', name: 'Jim', transliteration: 'j', isolated: 'ج', initial: 'جـ', medial: 'ـجـ', final: 'ـج', exampleWord: 'جهان', exampleTransliteration: 'jahān', exampleMeaningEn: 'World', exampleMeaningZh: '世界' },
  { char: 'چ', name: 'Che', transliteration: 'ch', isolated: 'چ', initial: 'چـ', medial: 'ـچـ', final: 'ـچ', exampleWord: 'چای', exampleTransliteration: 'chāy', exampleMeaningEn: 'Tea', exampleMeaningZh: '茶' },
  { char: 'ح', name: 'He', transliteration: 'h', isolated: 'ح', initial: 'حـ', medial: 'ـحـ', final: 'ـح', exampleWord: 'حول', exampleTransliteration: 'hol', exampleMeaningEn: 'Towel', exampleMeaningZh: '毛巾' },
  { char: 'خ', name: 'Khe', transliteration: 'kh', isolated: 'خ', initial: 'خـ', medial: 'ـخـ', final: 'ـخ', exampleWord: 'خانه', exampleTransliteration: 'khāne', exampleMeaningEn: 'House', exampleMeaningZh: '房子' },
  { char: 'د', name: 'Dāl', transliteration: 'd', isolated: 'د', initial: 'د', medial: 'ـد', final: 'ـد', exampleWord: 'دست', exampleTransliteration: 'dast', exampleMeaningEn: 'Hand', exampleMeaningZh: '手' },
  { char: 'ذ', name: 'Zāl', transliteration: 'z', isolated: 'ذ', initial: 'ذ', medial: 'ـذ', final: 'ـذ', exampleWord: 'ذرت', exampleTransliteration: 'zorrat', exampleMeaningEn: 'Corn', exampleMeaningZh: '玉米' },
  { char: 'ر', name: 'Re', transliteration: 'r', isolated: 'ر', initial: 'ر', medial: 'ـر', final: 'ـر', exampleWord: 'روز', exampleTransliteration: 'ruz', exampleMeaningEn: 'Day', exampleMeaningZh: '天' },
  { char: 'ز', name: 'Ze', transliteration: 'z', isolated: 'ز', initial: 'ز', medial: 'ـز', final: 'ـز', exampleWord: 'زن', exampleTransliteration: 'zan', exampleMeaningEn: 'Woman', exampleMeaningZh: '女人' },
  { char: 'ژ', name: 'Zhe', transliteration: 'zh', isolated: 'ژ', initial: 'ژ', medial: 'ـژ', final: 'ـژ', exampleWord: 'ژاکت', exampleTransliteration: 'zhākat', exampleMeaningEn: 'Jacket', exampleMeaningZh: '夾克' },
  { char: 'س', name: 'Sin', transliteration: 's', isolated: 'س', initial: 'سـ', medial: 'ـسـ', final: 'ـس', exampleWord: 'سیب', exampleTransliteration: 'sib', exampleMeaningEn: 'Apple', exampleMeaningZh: '蘋果' },
  { char: 'ش', name: 'Shin', transliteration: 'sh', isolated: 'ش', initial: 'شـ', medial: 'ـشـ', final: 'ـش', exampleWord: 'شب', exampleTransliteration: 'shab', exampleMeaningEn: 'Night', exampleMeaningZh: '夜晚' },
  { char: 'ص', name: 'Sād', transliteration: 's', isolated: 'ص', initial: 'صـ', medial: 'ـصـ', final: 'ـص', exampleWord: 'صندلی', exampleTransliteration: 'sandali', exampleMeaningEn: 'Chair', exampleMeaningZh: '椅子' },
  { char: 'ض', name: 'Zād', transliteration: 'z', isolated: 'ض', initial: 'ضـ', medial: 'ـضـ', final: 'ـض', exampleWord: 'ضرب', exampleTransliteration: 'zarb', exampleMeaningEn: 'Beat/Rhythm', exampleMeaningZh: '節奏' },
  { char: 'ط', name: 'Tā', transliteration: 't', isolated: 'ط', initial: 'ط', medial: 'ـطـ', final: 'ـط', exampleWord: 'طوطی', exampleTransliteration: 'tuti', exampleMeaningEn: 'Parrot', exampleMeaningZh: '鸚鵡' },
  { char: 'ظ', name: 'Zā', transliteration: 'z', isolated: 'ظ', initial: 'ظ', medial: 'ـظـ', final: 'ـظ', exampleWord: 'ظرف', exampleTransliteration: 'zarf', exampleMeaningEn: 'Dish', exampleMeaningZh: '盤子' },
  { char: 'ع', name: 'Ayn', transliteration: 'a / \'', isolated: 'ع', initial: 'عـ', medial: 'ـعـ', final: 'ـع', exampleWord: 'عسل', exampleTransliteration: 'asal', exampleMeaningEn: 'Honey', exampleMeaningZh: '蜂蜜' },
  { char: 'غ', name: 'Ghayn', transliteration: 'gh', isolated: 'غ', initial: 'غـ', medial: 'ـغـ', final: 'ـغ', exampleWord: 'غذا', exampleTransliteration: 'ghazā', exampleMeaningEn: 'Food', exampleMeaningZh: '食物' },
  { char: 'ف', name: 'Fe', transliteration: 'f', isolated: 'ف', initial: 'فـ', medial: 'ـفـ', final: 'ـف', exampleWord: 'فارسی', exampleTransliteration: 'fārsi', exampleMeaningEn: 'Persian', exampleMeaningZh: '波斯語' },
  { char: 'ق', name: 'Qāf', transliteration: 'q / gh', isolated: 'ق', initial: 'قـ', medial: 'ـقـ', final: 'ـق', exampleWord: 'قلم', exampleTransliteration: 'qalam', exampleMeaningEn: 'Pen', exampleMeaningZh: '筆' },
  { char: 'ک', name: 'Kāf', transliteration: 'k', isolated: 'ک', initial: 'کـ', medial: 'ـکـ', final: 'ـک', exampleWord: 'کتاب', exampleTransliteration: 'ketāb', exampleMeaningEn: 'Book', exampleMeaningZh: '書' },
  { char: 'گ', name: 'Gāf', transliteration: 'g', isolated: 'گ', initial: 'گـ', medial: 'ـگـ', final: 'ـگ', exampleWord: 'گربه', exampleTransliteration: 'gorbe', exampleMeaningEn: 'Cat', exampleMeaningZh: '貓' },
  { char: 'ل', name: 'Lām', transliteration: 'l', isolated: 'ل', initial: 'لـ', medial: 'ـلـ', final: 'ـل', exampleWord: 'لب', exampleTransliteration: 'lab', exampleMeaningEn: 'Lip', exampleMeaningZh: '嘴唇' },
  { char: 'م', name: 'Mim', transliteration: 'm', isolated: 'م', initial: 'مـ', medial: 'ـمـ', final: 'ـم', exampleWord: 'mādar', exampleTransliteration: 'mādar', exampleMeaningEn: 'Mother', exampleMeaningZh: '母親' },
  { char: 'ن', name: 'Nun', transliteration: 'n', isolated: 'ن', initial: 'نـ', medial: 'ـنـ', final: 'ـن', exampleWord: 'نان', exampleTransliteration: 'nān', exampleMeaningEn: 'Bread', exampleMeaningZh: '麵包' },
  { char: 'و', name: 'Vāv', transliteration: 'v / u', isolated: 'و', initial: 'و', medial: 'ـو', final: 'ـو', exampleWord: 'ورزش', exampleTransliteration: 'varzesh', exampleMeaningEn: 'Sport', exampleMeaningZh: '運動' },
  { char: 'ه', name: 'He', transliteration: 'h', isolated: 'ه', initial: 'هـ', medial: 'ـهـ', final: 'ـه', exampleWord: 'هلو', exampleTransliteration: 'holu', exampleMeaningEn: 'Peach', exampleMeaningZh: '桃子' },
  { char: 'ی', name: 'Ye', transliteration: 'y / i', isolated: 'ی', initial: 'یـ', medial: 'ـیـ', final: 'ـی', exampleWord: 'یخ', exampleTransliteration: 'yakh', exampleMeaningEn: 'Ice', exampleMeaningZh: '冰' },
];

export const GAME_LEVELS: LevelConfig[] = [
  // --- Stage 1: Foundation (基礎階段) ---
  {
    id: 1,
    titleEn: "Alphabet & Sounds",
    titleZh: "字母與發音",
    titleJa: "文字と発音",
    titleKo: "字母와 發音",
    descriptionEn: "Master the script and basic pronunciation rules.",
    descriptionZh: "掌握字母書寫與基礎發音規則。",
    topic: "Persian Alphabet, Vowels, and Connecting Letters",
    difficulty: "Foundation",
    stageLabelEn: "Stage 1: Foundation",
    stageLabelZh: "第一階段：基礎",
    stageLabelJa: "第1段階：基礎",
    stageLabelKo: "第1段階：基礎",
    icon: "Type"
  },
  {
    id: 2,
    titleEn: "Basics & Numbers",
    titleZh: "基礎詞彙與數字",
    titleJa: "基本単語と数字",
    titleKo: "基礎語彙와 數字",
    descriptionEn: "Numbers 0-20, People, and Basic Objects.",
    descriptionZh: "數字 0-20、人物與基本物品。",
    topic: "Persian Numbers, Basic Pronouns, and Common Objects",
    difficulty: "Foundation",
    stageLabelEn: "Stage 1: Foundation",
    stageLabelZh: "第一階段：基礎",
    stageLabelJa: "第1段階：基礎",
    stageLabelKo: "第1段階：基礎",
    icon: "Hash"
  },
  {
    id: 3,
    titleEn: "Greetings & Intros",
    titleZh: "問候與自我介紹",
    titleJa: "挨拶と自己紹介",
    titleKo: "問候와 自我介紹",
    descriptionEn: "Saying hello, goodbye, and introducing yourself.",
    descriptionZh: "打招呼、道別與自我介紹。",
    topic: "Common Greetings, Polite Phrases, and Introductions",
    difficulty: "Foundation",
    stageLabelEn: "Stage 1: Foundation",
    stageLabelZh: "第一階段：基礎",
    stageLabelJa: "第1段階：基礎",
    stageLabelKo: "第1段階：基礎",
    icon: "Hand"
  },

  // --- Stage 2: Beginner Communication (初級溝通) ---
  {
    id: 4,
    titleEn: "Basic Sentences",
    titleZh: "基本句型",
    titleJa: "基本文型",
    titleKo: "基本句型",
    descriptionEn: "Affirmative, Negative, and Questions.",
    descriptionZh: "肯定句、否定句與疑問句。",
    topic: "Simple Sentence Structure (Subject-Object-Verb), To Be, To Have",
    difficulty: "Beginner",
    stageLabelEn: "Stage 2: Beginner",
    stageLabelZh: "第二階段：初級溝通",
    stageLabelJa: "第2段階：初級会話",
    stageLabelKo: "第2段階：初級疏通",
    icon: "MessageCircle"
  },
  {
    id: 5,
    titleEn: "Daily Routines",
    titleZh: "日常生活",
    titleJa: "日常生活",
    titleKo: "日常生活",
    descriptionEn: "Time, days of the week, and routine verbs.",
    descriptionZh: "時間、星期與日常慣例動詞。",
    topic: "Telling Time, Days of Week, Simple Present Verbs",
    difficulty: "Beginner",
    stageLabelEn: "Stage 2: Beginner",
    stageLabelZh: "第二階段：初級溝通",
    stageLabelJa: "第2段階：初級会話",
    stageLabelKo: "第2段階：初級疏通",
    icon: "Clock"
  },
  {
    id: 6,
    titleEn: "Out & About",
    titleZh: "外出情境",
    titleJa: "外出と買い物",
    titleKo: "外出情境",
    descriptionEn: "Shopping, ordering food, and asking directions.",
    descriptionZh: "購物、點餐與問路。",
    topic: "Vocabulary for Shopping, Restaurants, and Directions",
    difficulty: "Beginner",
    stageLabelEn: "Stage 2: Beginner",
    stageLabelZh: "第二階段：初級溝通",
    stageLabelJa: "第2段階：初級会話",
    stageLabelKo: "第2段階：初級疏通",
    icon: "MapPin"
  },

  // --- Stage 3: Intermediate Ability (中級能力) ---
  {
    id: 7,
    titleEn: "Connecting Ideas",
    titleZh: "複句與連接詞",
    titleJa: "接続詞と複文",
    titleKo: "複句와 連接詞",
    descriptionEn: "Using 'and', 'but', 'because' to make complex sentences.",
    descriptionZh: "使用「和」、「但是」、「因為」造長句。",
    topic: "Conjunctions, Complex Sentences, and Linking words",
    difficulty: "Intermediate",
    stageLabelEn: "Stage 3: Intermediate",
    stageLabelZh: "第三階段：中級能力",
    stageLabelJa: "第3段階：中級能力",
    stageLabelKo: "第3段階：中級能力",
    icon: "GitMerge"
  },
  {
    id: 8,
    titleEn: "Politeness & Formality",
    titleZh: "敬語與語法細節",
    titleJa: "敬語と文法",
    titleKo: "敬語와 語法",
    descriptionEn: "Formal 'You' and polite verbal endings.",
    descriptionZh: "正式的「您」與禮貌語尾。",
    topic: "Formal vs Informal Language (Ta'arof basics)",
    difficulty: "Intermediate",
    stageLabelEn: "Stage 3: Intermediate",
    stageLabelZh: "第三階段：中級能力",
    stageLabelJa: "第3段階：中級能力",
    stageLabelKo: "第3段階：中級能力",
    icon: "Crown"
  },
  {
    id: 9,
    titleEn: "Hobbies & Health",
    titleZh: "興趣與健康",
    titleJa: "趣味と健康",
    titleKo: "興趣와 健康",
    descriptionEn: "Discussing sports, health, and personal interests.",
    descriptionZh: "討論運動、健康與個人興趣。",
    topic: "Vocabulary for Hobbies, Sports, Body parts, and Health",
    difficulty: "Intermediate",
    stageLabelEn: "Stage 3: Intermediate",
    stageLabelZh: "第三階段：中級能力",
    stageLabelJa: "第3段階：中級能力",
    stageLabelKo: "第3段階：中級能力",
    icon: "Heart"
  },

  // --- Stage 4: Advanced Application (進階運用) ---
  {
    id: 10,
    titleEn: "Past & Future",
    titleZh: "過去與未來",
    titleJa: "過去と未来",
    titleKo: "過去와 未來",
    descriptionEn: "Storytelling using Past and Future tenses.",
    descriptionZh: "使用過去式與未來式說故事。",
    topic: "Simple Past, Past Continuous, and Future Tenses",
    difficulty: "Advanced",
    stageLabelEn: "Stage 4: Advanced",
    stageLabelZh: "第四階段：進階運用",
    stageLabelJa: "第4段階：上級応用",
    stageLabelKo: "第4段階：進階運用",
    icon: "History"
  },
  {
    id: 11,
    titleEn: "Abstract Topics",
    titleZh: "抽象主題",
    titleJa: "抽象的な話題",
    titleKo: "抽象主題",
    descriptionEn: "Passive voice, indirect speech, and opinions.",
    descriptionZh: "被動語態、間接引語與表達意見。",
    topic: "Passive Voice, Reported Speech, Expressing Opinions",
    difficulty: "Advanced",
    stageLabelEn: "Stage 4: Advanced",
    stageLabelZh: "第四階段：進階運用",
    stageLabelJa: "第4段階：上級応用",
    stageLabelKo: "第4段階：進階運用",
    icon: "BrainCircuit"
  },
  {
    id: 12,
    titleEn: "Reading & Writing",
    titleZh: "長文閱讀與寫作",
    titleJa: "読解と作文",
    titleKo: "長文閱讀과 寫作",
    descriptionEn: "Reading short texts and structuring paragraphs.",
    descriptionZh: "閱讀短文與段落架構。",
    topic: "Reading Comprehension, Connecting Paragraphs, Written Persian",
    difficulty: "Advanced",
    stageLabelEn: "Stage 4: Advanced",
    stageLabelZh: "第四階段：進階運用",
    stageLabelJa: "第4段階：上級応用",
    stageLabelKo: "第4段階：進階運用",
    icon: "BookOpen"
  },

  // --- Stage 5: Fluency & Culture (流利與文化) ---
  {
    id: 13,
    titleEn: "Idioms & Slang",
    titleZh: "慣用語與俚語",
    titleJa: "慣用句とスラング",
    titleKo: "慣用語와 俚語",
    descriptionEn: "Common Persian idioms and street language.",
    descriptionZh: "常見波斯語慣用語與街頭用語。",
    topic: "Persian Idioms, Proverbs, and Colloquial Slang",
    difficulty: "Fluency",
    stageLabelEn: "Stage 5: Fluency",
    stageLabelZh: "第五階段：流利與文化",
    stageLabelJa: "第5段階：流暢さと文化",
    stageLabelKo: "第5段階：流利와 文化",
    icon: "Sparkles"
  },
  {
    id: 14,
    titleEn: "Culture & Poetry",
    titleZh: "文化與詩歌",
    titleJa: "文化と詩",
    titleKo: "文化와 詩歌",
    descriptionEn: "Understanding Persian art, poetry, and traditions.",
    descriptionZh: "了解波斯藝術、詩歌與傳統。",
    topic: "Persian Poetry basics (Hafez/Rumi), Cultural Traditions",
    difficulty: "Fluency",
    stageLabelEn: "Stage 5: Fluency",
    stageLabelZh: "第五階段：流利與文化",
    stageLabelJa: "第5段階：流暢さと文化",
    stageLabelKo: "第5段階：流利와 文化",
    icon: "Feather"
  },
  {
    id: 15,
    titleEn: "Professional Life",
    titleZh: "專業領域",
    titleJa: "ビジネス用語",
    titleKo: "專業領域",
    descriptionEn: "Business vocabulary and news media.",
    descriptionZh: "商業詞彙與新聞媒體。",
    topic: "Business Persian, Media Vocabulary, Current Events",
    difficulty: "Fluency",
    stageLabelEn: "Stage 5: Fluency",
    stageLabelZh: "第五階段：流利與文化",
    stageLabelJa: "第5段階：流暢さと文化",
    stageLabelKo: "第5段階：流利와 文化",
    icon: "Briefcase"
  }
];

export const UI_STRINGS: Record<Language, UIContent> = {
  [Language.EN]: {
    title: 'FarsiFlow',
    subtitle: 'Master the Persian Language',
    homeTab: 'Home',
    learnTab: 'Alphabet',
    practiceTab: 'Curriculum',
    vocabTab: 'Words',
    tutorTab: 'AI Tutor',
    connectTitle: 'Letter Forms',
    connectDesc: 'Persian letters change shape depending on their position in a word.',
    pronounceBtn: 'Listen',
    example: 'Example',
    chatPlaceholder: 'Ask about Persian grammar or culture...',
    chatSend: 'Send',
    loading: 'Generating Content...',
    welcomeTutor: 'Persian Tutor',
    tutorIntro: 'I can help you understand grammar, translate phrases, or explain cultural nuances. Ask me anything!',
    startLevel: 'Start Lesson',
    continueLevel: 'Continue',
    stageIndicator: 'Stage',
    locked: 'Locked',
    quizTitle: 'Quiz',
    nextBtn: 'Continue',
    checkBtn: 'Check Answer',
    correct: 'Excellent!',
    incorrect: 'Not quite right',
    completed: 'Stage Complete!',
    xpEarned: 'XP Earned',
    wordsLearned: 'Words Collected',
    backHome: 'Back to Path',
    noWords: 'No words collected yet. Complete lessons to build your bank!',
    searchVocab: 'Search vocabulary...',
    handoutTitle: 'Lesson Handout',
    startQuizBtn: 'Start Quiz',
    vocabSection: 'New Vocabulary',
    grammarSection: 'Grammar Concept',
    sentencesSection: 'Usage Examples',
    cultureSection: 'Cultural Insight',
    loginTitle: 'Sign In',
    signupTitle: 'Create Account',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    nameLabel: 'Full Name',
    loginBtn: 'Sign In',
    signupBtn: 'Create Account',
    switchNoAccount: "Don't have an account? Sign up",
    switchHasAccount: 'Already have an account? Sign in',
    logout: 'Sign Out',
    profile: 'Profile',
    welcomeBack: 'Welcome back,',
    authError: 'Invalid email or password',
    authSuccess: 'Success!',
    fieldRequired: 'All fields are required',
    dailyFactTitle: 'Persian Insight of the Moment',
    didYouKnow: 'Did you know?',
    refreshFact: 'New Fact',
    continueJourney: 'Continue Course',
    totalXp: 'Total XP',
    currentLevel: 'Current Level',
    streak: 'Day Streak',
    days: 'days',
    leaderboardTitle: 'Class Rankings',
    you: 'You',
    // Modals
    streakTitle: 'Daily Streak',
    streakDesc: 'Practice every day to keep your streak alive!',
    xpTitle: 'Your Experience',
    xpDesc: 'Earn XP by completing lessons and quizzes.',
    nextRank: 'until next rank',
    selectStage: 'Select Stage',
    stage: 'Stage',
    playBtn: 'Play',
    replayBtn: 'Review',
    closeBtn: 'Close'
  },
  [Language.ZH_TW]: {
    title: '波斯語通',
    subtitle: '掌握波斯語',
    homeTab: '首頁',
    learnTab: '字母表',
    practiceTab: '課程地圖',
    vocabTab: '單字庫',
    tutorTab: 'AI 導師',
    connectTitle: '字母形式',
    connectDesc: '波斯字母會根據其在單詞中的位置改變形狀。',
    pronounceBtn: '發音',
    example: '範例',
    chatPlaceholder: '詢問關於波斯語文法或文化...',
    chatSend: '發送',
    loading: '生成內容中...',
    welcomeTutor: '波斯語導師',
    tutorIntro: '我可以幫你理解文法、翻譯短語或解釋文化細節。隨時問我！',
    startLevel: '開始課程',
    continueLevel: '繼續學習',
    stageIndicator: '階段',
    locked: '未解鎖',
    quizTitle: '測驗',
    nextBtn: '繼續',
    checkBtn: '檢查答案',
    correct: '太棒了！',
    incorrect: '不太正確',
    completed: '階段完成！',
    xpEarned: '獲得經驗值',
    wordsLearned: '收集單字',
    backHome: '返回地圖',
    noWords: '尚未收集單字。完成課程來建立你的單字庫！',
    searchVocab: '搜尋單字...',
    handoutTitle: '單元講義',
    startQuizBtn: '開始測驗',
    vocabSection: '核心單字',
    grammarSection: '文法重點',
    sentencesSection: '例句練習',
    cultureSection: '文化小知識',
    loginTitle: '登入',
    signupTitle: '建立帳號',
    emailLabel: '電子郵件',
    passwordLabel: '密碼',
    nameLabel: '全名',
    loginBtn: '登入',
    signupBtn: '建立帳號',
    switchNoAccount: '還沒有帳號？註冊',
    switchHasAccount: '已經有帳號了？登入',
    logout: '登出',
    profile: '個人檔案',
    welcomeBack: '歡迎回來，',
    authError: '電子郵件或密碼錯誤',
    authSuccess: '成功！',
    fieldRequired: '所有欄位皆為必填',
    dailyFactTitle: '波斯文化小知識',
    didYouKnow: '你知道嗎？',
    refreshFact: '換一個',
    continueJourney: '繼續課程',
    totalXp: '總經驗值',
    currentLevel: '目前等級',
    streak: '連續天數',
    days: '天',
    leaderboardTitle: '班級排名',
    you: '你',
    streakTitle: '每日連續紀錄',
    streakDesc: '每天練習以保持你的連續紀錄！',
    xpTitle: '你的經驗值',
    xpDesc: '通過完成課程和測驗獲得 XP。',
    nextRank: '升級還需',
    selectStage: '選擇關卡',
    stage: '關卡',
    playBtn: '開始',
    replayBtn: '複習',
    closeBtn: '關閉'
  },
  [Language.JA]: {
    title: 'FarsiFlow',
    subtitle: 'ペルシャ語をマスターしよう',
    homeTab: 'ホーム',
    learnTab: '文字',
    practiceTab: 'コース',
    vocabTab: '単語帳',
    tutorTab: 'AI講師',
    connectTitle: '文字の形',
    connectDesc: 'ペルシャ文字は、単語内の位置によって形が変わります。',
    pronounceBtn: '発音',
    example: '例',
    chatPlaceholder: '文法や文化について質問してください...',
    chatSend: '送信',
    loading: 'コンテンツを生成中...',
    welcomeTutor: 'ペルシャ語チューター',
    tutorIntro: '文法の説明、翻訳、文化の解説など、何でも聞いてください！',
    startLevel: 'レッスン開始',
    continueLevel: '続ける',
    stageIndicator: 'ステージ',
    locked: 'ロック中',
    quizTitle: 'クイズ',
    nextBtn: '次へ',
    checkBtn: '答え合わせ',
    correct: '素晴らしい！',
    incorrect: '不正解です',
    completed: 'ステージクリア！',
    xpEarned: '獲得XP',
    wordsLearned: '習得した単語',
    backHome: 'マップへ戻る',
    noWords: 'まだ単語がありません。レッスンを完了して単語を集めましょう！',
    searchVocab: '単語を検索...',
    handoutTitle: 'レッスン教材',
    startQuizBtn: 'クイズ開始',
    vocabSection: '新しい単語',
    grammarSection: '文法ポイント',
    sentencesSection: '例文',
    cultureSection: '文化コラム',
    loginTitle: 'ログイン',
    signupTitle: 'アカウント作成',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    nameLabel: '氏名',
    loginBtn: 'ログイン',
    signupBtn: '作成する',
    switchNoAccount: 'アカウントをお持ちでないですか？登録',
    switchHasAccount: 'アカウントをお持ちですか？ログイン',
    logout: 'ログアウト',
    profile: 'プロフィール',
    welcomeBack: 'お帰りなさい、',
    authError: 'メールまたはパスワードが無効です',
    authSuccess: '成功！',
    fieldRequired: 'すべての項目を入力してください',
    dailyFactTitle: '今日のペルシャ知識',
    didYouKnow: '知っていましたか？',
    refreshFact: '更新',
    continueJourney: '学習を続ける',
    totalXp: '総XP',
    currentLevel: '現在のレベル',
    streak: '連続日数',
    days: '日',
    leaderboardTitle: 'ランキング',
    you: 'あなた',
    streakTitle: '連続記録',
    streakDesc: '毎日練習して記録を伸ばしましょう！',
    xpTitle: 'あなたの経験値',
    xpDesc: 'レッスンやクイズを完了してXPを獲得しましょう。',
    nextRank: '次のランクまで',
    selectStage: 'ステージ選択',
    stage: 'ステージ',
    playBtn: 'プレイ',
    replayBtn: '復習',
    closeBtn: '閉じる'
  },
  [Language.KO]: {
    title: 'FarsiFlow',
    subtitle: '波斯語(페르시아어) 完全征服',
    homeTab: '首頁',
    learnTab: '字母',
    practiceTab: '課程',
    vocabTab: '單語',
    tutorTab: 'AI 講師',
    connectTitle: '字母 形態',
    connectDesc: '波斯(페르시아) 字母는 單語 內 位置에 따라 形態가 變합니다.',
    pronounceBtn: '發音',
    example: '例示',
    chatPlaceholder: '文法이나 文化에 대해 質問하세요...',
    chatSend: '傳送',
    loading: '生成 中...',
    welcomeTutor: '波斯語 講師',
    tutorIntro: '文法, 飜譯, 文化 說明을 도와드립니다. 何든지 質問하세요!',
    startLevel: '授業 開始',
    continueLevel: '繼續',
    stageIndicator: '段階',
    locked: '潛金',
    quizTitle: '試驗',
    nextBtn: '繼續',
    checkBtn: '正答 確認',
    correct: '훌륭합니다!',
    incorrect: '틀렸습니다',
    completed: '段階 完成!',
    xpEarned: '獲得 經驗值',
    wordsLearned: '蒐集 單語',
    backHome: '地圖로 復歸',
    noWords: '蒐集된 單語가 없습니다. 授業를 完了하세요!',
    searchVocab: '單語 檢索...',
    handoutTitle: '講義 資料',
    startQuizBtn: '試驗 開始',
    vocabSection: '核心 單語',
    grammarSection: '文法 重點',
    sentencesSection: '例文 練習',
    cultureSection: '文化 常識',
    loginTitle: '登入',
    signupTitle: '計定 生成',
    emailLabel: '伊美逸(Email)',
    passwordLabel: '暗號(Password)',
    nameLabel: '姓名',
    loginBtn: '登入',
    signupBtn: '生成',
    switchNoAccount: '計定이 없으신가요? 登錄',
    switchHasAccount: '이미 計定이 있으신가요? 登入',
    logout: '登出',
    profile: '個人情報',
    welcomeBack: '歡迎합니다,',
    authError: '伊美逸 또는 暗號가 올바르지 않습니다',
    authSuccess: '成功!',
    fieldRequired: '모든 項目을 入力하세요',
    dailyFactTitle: '今日의 波斯 常識',
    didYouKnow: '알고 계셨나요?',
    refreshFact: '更新',
    continueJourney: '學習 繼續',
    totalXp: '總 經驗值',
    currentLevel: '現在 等級',
    streak: '連續 日數',
    days: '日',
    leaderboardTitle: '順位',
    you: '本人',
    streakTitle: '連續 記錄',
    streakDesc: '每日 練習하여 記錄을 維持하세요!',
    xpTitle: '經驗值',
    xpDesc: '授業와 試驗을 完了하여 XP를 獲得하세요.',
    nextRank: '다음 等級까지',
    selectStage: '段階 選擇',
    stage: '段階',
    playBtn: '始作',
    replayBtn: '復習',
    closeBtn: '닫기'
  }
};
